### ISSUE TITLE
Social Buttons display on frontend but nothing happens when clicked

### ISSUE THREAD

**Issue by mubmart7** [akeeba/sociallogin#101] opened 2023-08-04 12:20 UTC
The buttons display on both front and backend on my joomla 4 website but nothing happens when clicked on the front end. However, on the backend login page, they respond when clicked. 

Tried to check this issue on the list of submitted issues but could not find it.

What am I missing?

![Screenshot 2023-08-04 at 15-19-29 LOGIN](https://github.com/akeeba/sociallogin/assets/141418802/64842be8-58e1-4e07-adf6-f1799ac65cbe)

**Comment by nikosdion** [comment] 2023-08-04 12:36
I would guess that another plugin or module is causing a JavaScript error on the page, therefore the browser stops executing JavaScript (which is why the event handler of the buttons, written in JavaScript, does not execute).

**Comment by mubmart7** [comment] 2023-08-04 14:37
I have used chrome to remove any JavaScript that may cause the problem but still the buttons do not respond. 

The page is: https://www.workforce.lafabsolution.com/login

**Comment by nikosdion** [comment] 2023-08-04 16:32
Thanks for the link. The problem is rather obvious. Your template override for the login page is broken. It does not respect the settings set by the additional login buttons, namely the `class`.

If you are about to disagree, don't. The Web Authentication button which ships with Joomla! itself also does not work for the same reason.

Closing issue as invalid.

**Closed as not planned by nikosdion** 2023-08-04 16:32 UTC
Labels: invalid

**Comment by mubmart7** [comment] 2023-08-05 08:27
It now works. Please show some guidance on making the login page override for joomla 4. It is a simple procedure but many users may not know how to deal with it.

**Comment by nikosdion** [comment] 2023-08-05 08:53
I don’t think it’s appropriate for extension developers to document core Joomla! features. It is a duplication of effort with that of Joomla’s documentation team, and it puts the onus of updating such documentation on us even though any changes in Joomla are not under our control! This is an impossible ask. 

There is already documentation in Joomla’s documentation wiki for making template overrides: https://docs.joomla.org/J4.x:Template_Overrides The example is even for the login module. It stands to reason that overriding the output of com_users would let you make an override for the login page.

Ultimately, whenever you make a template override, it becomes your responsibility not to mess it up and keep it up to date. It is not the responsibility of third party extension developers, nor Joomla itself. The usual and reasonable complaint that you couldn’t know if the original template has changed is no longer valid since Joomla 4.0; every time you update Joomla! itself, or one of its extensions, Joomla! checks for changed template overrides and let’s you know in its main Control Panel page (assuming you don’t deliberately unpublish the quick icon plug-in or the quick icon admin module) and it’s Templates page.
