### ISSUE TITLE
Wechat social login

### ISSUE THREAD

**Issue by macaucentral** [akeeba/sociallogin#67] opened 2021-02-11 05:12 UTC
WeChat is a Chinese social media application that has nearly 1 billion active users each month.

Integration Guide:
https://janrain-education-center.knowledgeowl.com/home/wechat-social-login-configuration-guide

**Comment by nikosdion** [comment] 2021-02-11 05:28
Duplicate of https://github.com/akeeba/sociallogin/issues/12 As I had written in May 2019 on that issue, explaining why I can't integrate it:

> WeChat does not report the user's email address, see http://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/web/login/getting-user-profile#login_getting-user-profile As a result we cannot use it to log in a user who has not already linked WeChat to their Joomla user profile, nor can we use it to create new Joomla user accounts. This does not satisfy the minimum required set of features for inclusion in SocialLogin. Therefore login with WeChat will not be developed.

The documentation is now in https://developers.weixin.qq.com/doc/oplatform/en/Website_App/WeChat_Login/Wechat_Login.html and https://developers.weixin.qq.com/doc/oplatform/en/Third-party_Platforms/api/api_get_authorizer_info.html but the core explanation still applies: there is no way to get an email address, therefore the minimum requirements for integration are not satisfied.

**Closed as completed by nikosdion** 2021-02-11 05:28 UTC
Labels: duplicate
